#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@caldera.de>
# Rewritten to use lists instead of if-statements.
#

subdir-y :=     serial
subdir-$(CONFIG_MTD) += mtd

include $(TOPDIR)/Rules.make
